### ISSUE TITLE
Slow parseCmakeListsForTests for large workspaces

### ISSUE THREAD

**Issue by nalinor** [betwo/vscode-catkin-tools#11]
First, thumbs up for the great work.
Here's my issue. 
Every run of ```vscode.workspace.findFiles``` seems to take (for my WS) 100ms, whereas if I use fast-glob it takes around 1ms. 

Also, I don't follow symlinks during search and the exclude patterns seem correct.
From profiling, I think there is a lot of overhead in spawning process for the repeated searches.

**Comment by nalinor** [comment]
This is the line I was referring to.
https://github.com/betwo/vscode-catkin-tools/blob/5ba13dcc25d980271b230099238d5ea31488f143/src/catkin_workspace.ts#L118

**Comment by betwo** [comment]
Thanks for the report, @nalinor!

I have been able to reproduce similar timings in my workspace now.

> Also, I don't follow symlinks during search and the exclude patterns seem correct.

The change to `fast-glob` should not be problematic.
I would keep `followSymbolicLinks`, however, to support symlinked packages with tests.

In a minute, I'll prepare another release (1.5.3). Could you please give feedback, if you also see the expected speed up?

**Comment by nalinor** [comment]
Will do

**Comment by nalinor** [comment]
Tested it. Works.
Now the parsingForTests function takes (according to console.time...) like only a few ms instead of 150ms. For large workspaces, this improves things tremendously. 
Thanks so much for reacting so quickly!

**Comment by betwo** [comment]
Thank you for the feedback, glad to hear it works!
