### ISSUE TITLE
Test Explorer doesn't update catkin test result icon

### ISSUE THREAD

**Issue by rcabg** [betwo/vscode-catkin-tools#18]
Not sure if this goes here or in Test Explorer UI extension. 

For me, catkin tests (using gtests) are correctly detected and executed, but I cannot see icon results updated, keeping always a gray circle with a square in the middle.

If any test fails, the parsed result is correctly shown in the PROBLEMS tab in vscode. If tests succeed, nothing appears. In both cases, the gray icon with black square remains.

Is this the expected behavior? Should appear a "green check" or "red cross" when tests are executed?

Thanks in advance!

**Comment by betwo** [comment]
This is definitely not the intended behavior, thank you for reporting.

The extension currently assumes that your default shell is `bash` (it uses built-in bash commands like `source`, `pushd` and `popd`)
When using `sh`, for example, I see the same behavior.

Which is your default shell? If it is `bash`, please [attach your log outputs.](../wiki/DebuggingInstalled).

**Comment by betwo** [comment]
Hey @rcabg, I think the bug is fixed with version `1.12.0`. Could you please check with your setup?
Thank you!

**Comment by rcabg** [comment]
Hello @betwo, 

Sorry for the delay! I can confirm the bug is solved with version 1.12.0 in my setup. 

Thanks for your quick response!
