### ISSUE TITLE
[Feature Request] Creating task configurations with a 'group' section

### ISSUE THREAD

**Issue by tejaswid** [betwo/vscode-catkin-tools#28]
In vscode when one presses `ctrl+shift+p` > `Tasks: Configure Task` > `catkin_build: build` or `catkin_build: build current package` or `catkin_build: run current package tests`, the configuration generated in `.vscode/tasks.json` does not contain the **group** section.

As a result these configurations are not available in the drop down menu when one presses `ctrl+shift+b`. However, if the .json file is modified to include the **group** section as in the snippet below, they can be made accessible in the drop down menu.

```json
{
    "type": "catkin_build",
    "task": "build current package",
    "problemMatcher": [
       "$catkin-gcc",
       "$catkin-cmake"
    ],
    "group": "build",
    "label": "catkin_build: build current package"
},
```

It would be nice if this can be generated automatically.

**Comment by betwo** [comment]
Hey @tejaswid, good catch. This will be release with the next version, not sure when exactly though.
