### ISSUE TITLE
Running tests with test explorer runs from install space

### ISSUE THREAD

**Issue by bochen87** [betwo/vscode-catkin-tools#36]
Hi,

I have some test assets that are sitting in my test/assets folder that my tests use. Now when I run the tests using the test explorer, it somehow looks in the INSTALL SPACE for those files, meaning I'd have to add my test assets to the CMakeLists.txt install instructions. 
Is there a way to specify that? Is that a bug?

**Comment by betwo** [comment]
Hi!

Can you give me an example of how your tests are locating the assets?
Are they assuming something about the working directory?
Can you run the tests when you `source` the install space?

**Comment by bochen87** [comment]
I do `ros::package::getPath("my_package_name") + "test/assets/test_assets.bag"` to get my assets. 
`ros::package::getPath("my_package_name")` unfortunately resolves to `/path/to/my/install/space/share/my_package_name` instead of `/path/to/my/source/folder/my_package_name`

**Comment by betwo** [comment]
Ah I see. 

I slightly disagree with the prioritization of `devel` vs `install` on your PR:
If the install space is enabled in catkin, then sourcing the install space should also be sufficient to run all binaries.
So technically, you should actually install your testing assets with your test binaries.

However, I think adding an option (as in your PR) can definitely be done.
The only thing I would like to change is the default, i.e. have `useInstallSpace` default to `true`.

Would that be okay for you?

**Comment by bochen87** [comment]
sounds good!

**Comment by betwo** [comment]
Thank you very much! The PR is merged and will be part of the next release.
