### ISSUE TITLE
TYPED_TESTS are not supported

### ISSUE THREAD

**Issue by VinRud** [betwo/vscode-catkin-tools#38]
TYPED_TESTS and TYPED_TESTS_P are currently not supported, see documentation:
https://google.github.io/googletest/advanced.html#typed-tests

**Comment by betwo** [comment]
Hi @VinRud,

thanks for reaching out! I just created a pre-release for the next version:
https://github.com/betwo/vscode-catkin-tools/releases/tag/3.3.0

This should allow you to trigger `TYPED_TEST_*` style test cases.

Could you please give it a test run?

**Comment by VinRud** [comment]
thanks :)
