### ISSUE TITLE
Remove dependency on the vscode-test-explorer

### ISSUE THREAD

**Issue by rickstaa** [betwo/vscode-catkin-tools#42]
The vscode native test API has been finalized in vscode [v1.59](https://github.com/microsoft/vscode/releases/tag/1.59.0). As a result [vscode-test-explorer](https://github.com/hbenl/vscode-test-explorer#migrating-to-native-testing) will be deprecated (see [this announcement](https://github.com/hbenl/vscode-test-explorer#migrating-to-native-testing)). I think we therefore the dependency on [vscode-test-explorer](https://github.com/hbenl/vscode-test-explorer) can be removed (see #41).

**Comment by betwo** [comment]
Hi @rickstaa, thank you for the PR. 

I'll test this as soon as possible!

**Comment by betwo** [comment]
The dependency is not there anymore. Thank you for triggering this
