### ISSUE TITLE
Terminal colors bug

### ISSUE THREAD

**Issue by bennaa** [betwo/vscode-catkin-tools#47]
Hi - first of all thanks for the great extension!
Building the package using this extension gives the following output in terminal
![catkin_tools](https://user-images.githubusercontent.com/43421249/178982280-fc09720b-ed53-4a8d-91de-6071b4c8b758.png)
while if I type directly in vscode terminal the command to build my package the output is the following
![terminal](https://user-images.githubusercontent.com/43421249/178982587-2001765b-f63a-4d14-94f5-d66b26230eab.png)
Is there a way to have the output more visually understandable with colors as the second one?

**Comment by betwo** [comment]
Hi @bennaa, thank you for the feedback!

In past releases, the output was colored, but then we switched to a virtual terminal in vscode, which currently does not show colors.

Let's merge this issue with #45 and tackle them together.
