### ISSUE TITLE
vscode's clang-tidy integration doesn't report the same warnings / errors as clang-tidy started from the command line

### ISSUE THREAD

**Issue by rsarrazin2** [betwo/vscode-catkin-tools#50]
Since December 2021, [vscode's C/C++ extension features native clang-tidy integration](https://devblogs.microsoft.com/cppblog/visual-studio-code-c-december-2021-update-clang-tidy/) and the warnings / errors appear in the Problems pane.

Given code requiring e.g. C++14, it looks like, when used in conjunction with the catkin-tools extension, the integrated clang-tidy configuration doesn't look up the right compile_commands.json, if looking up any. The symptoms are the problems pane showing compilation errors while the actual compilation with `catkin build` is fine and the manually executed clang-tidy doesn't report errors.

Here some steps to reproduce:
```
# CMakeLists.txt
cmake_minimum_required(VERSION 3.8)
project(mwe)

add_library(${PROJECT_NAME} src/min_working_example.cpp)
```

```xml
<?xml version="1.0"?>
<package format="2">
  <name>mwe</name>
  <version>0.0.0</version>
  <description>description</description>
  <maintainer email="example@example.com">maintainer</maintainer>
  <license>license</license>

  <buildtool_depend>catkin</buildtool_depend>
</package>
```

```c++
struct DefaultInitializedAggregate
{
    int part1{};
    int part2{};
};

auto Do() -> DefaultInitializedAggregate { return {12, 27}; }

int main()
{
    Do();
    return 0;
}
```

The latter code doesn't compile with C++11 (https://godbolt.org/z/nnc7fevx8) but does with C++14 (https://godbolt.org/z/Gsbz9vnMx).

The same happens with the local builds:
```bash
# Doesn't pass
catkin config --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=11 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_CXX_EXTENSIONS=OFF
catkin build mwe

# Passes
catkin config --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_CXX_EXTENSIONS=OFF
catkin build mwe
```

When building the latter configuration, the integrated clang-tidy brings the following errors (the magic number warnings are only there to manifest clang-tidy's working):
![image](https://user-images.githubusercontent.com/108058522/217814832-771615dd-d497-4716-ae3b-1f74a4dcaf2f.png)

Running clang-tidy manually doesn't:
```
$ clang-tidy-15 -p build/mwe src/min_working_example/src/min_working_example.cpp 
8 warnings generated.
/workspace/src/min_working_example/src/min_working_example.cpp:7:52: warning: 12 is a magic number; consider replacing it with a named constant [cppcoreguidelines-avoid-magic-numbers,readability-magic-numbers]
auto Do() -> DefaultInitializedAggregate { return {12, 27}; }
                                                   ^
/workspace/src/min_working_example/src/min_working_example.cpp:7:56: warning: 27 is a magic number; consider replacing it with a named constant [cppcoreguidelines-avoid-magic-numbers,readability-magic-numbers]
auto Do() -> DefaultInitializedAggregate { return {12, 27}; }
                                                       ^
```

Expected behavior: The integrated clang-tidy shall output the same results as the manually started one when used in conjunction with catkin and its vscode extension.

**Comment by rsarrazin2** [comment]
Notes:
* The catkin extension is very useful in every other aspects, thanks for that!
* It's good and funny to see the name of good old colleagues on such projects. Thanks for your work, Sebastian!

**Comment by rsarrazin2** [comment]
Note that I tried to find out how the C/C++ extension picks up the build path for the integrated clang-tidy analysis, but I failed at understanding the code, so I'm sorry I don't come up with a pull request.

**Comment by betwo** [comment]
Hi @rsarrazin2, true, it has been a while, thank you for the feedback! 

I was able to reproduce this base on your example:
![image](https://user-images.githubusercontent.com/4789818/218194750-1b08e18d-9116-4a34-b61f-f6e4d34434c8.png)

When I set 
```json
"catkin_tools.cppStandard": "c++17"
```
in my settings, the problem goes away:
![image](https://user-images.githubusercontent.com/4789818/218194905-1a5577fc-d985-4727-8a94-18a6998fc932.png)

Could you maybe check, if that is the same for you?

The c++ version is currently not read from the `compile_commands.json` file, but we could try to parse this per file.
I'll look into this a bit more.

**Comment by betwo** [comment]
I think there is a simple solution for this, pre-release 4.6.0 should do it.
Could you please check if the problem still occurs for you?

**Comment by rsarrazin2** [comment]
I can already confirm that `"catkin_tools.cppStandard": "c++14"` helps. I'll test the mentioned pre-release 4.6.0 as soon as possible. Can you shortly elaborate on which changes of this release might mitigate this issue?

**Comment by betwo** [comment]
So this extension registers itself as a C++ configuration provider.
Clang-tidy is using the provided configuration when being run.

Before, the provided `cppStandard` was always that configured in `catkin_tools.cppStandard`, which is why setting that to `c++14` solves the problem.

With the new release, the standard is inferred from the actual compiler arguments used. This allows different compilation units to use different c++ standards instead of configuring one for the whole workspace.

**Comment by rsarrazin2** [comment]
I could test with the version updated on 10.02.2023 which I assume is the 4.6.0. After removing `"catkin_tools.cppStandard": "c++14"`(which, I repeat, was already successful), the problem is still gone. The only irritating part is this setting then defaulting to c++11 (but, as you described it, correctly ignored in favor of the compiler option's).

Maybe [this hint](https://github.com/betwo/vscode-catkin-tools/blob/0c16ab3976f3f0d8373f5f53cfee5d883f8abbca/package.json#L78) could be enhanced to "C++ standard to use if the compiler options don't define it (see C_CPP extension)".

Thanks for your quick and effective support! As far as I'm concerned, the issue can be closed.

**Comment by rsarrazin2** [comment]
Actually it didn't work when resetting `catkin_tools.cppStandard` but I saw that the version 10.02.2023 was the 4.4.1. I switched to the pre-release version and I got the pre-release 4.6.0 (release date: 10.02.2023 as well) which then worked as described.

Until the official release I'll manually pin the version to 4.6.0 in the devcontainer.json.

**Comment by betwo** [comment]
V 4.7.0 (no pre-release) should be live now with an updated docscring for the default `cppStandard`.

Thank you for test driving this!
