### ISSUE TITLE
Optional flags for "build current package"

### ISSUE THREAD

**Issue by stribor14** [betwo/vscode-catkin-tools#54]
Is there some way to change flags passed to catkin_tools?

For example, when running the "build current package" task, I do not want `-v --no-deps` flags since often we rebuild only parts of our system (mainly the dependencies of the current package we work on). As it stands now, the build process is always verbose and builds only this specific package

[I transitioned to vscode recently so maybe I'm unaware of how to remove those flags]

edit: If flags are not configurable, maybe add another type of task "Build current package with dependencies"

**Comment by betwo** [comment]
Hi @stribor14!

We can add such a task. Either we add the "build current package with dependencies", or we add a "generic" build task with customizable flags.

Which approach would you prefer? My guess is that the generic solution is more useful for other cases in the future, right?

**Comment by betwo** [comment]
Just published a new version (4.8.0) that supports both:

* `build with custom parameters` will load custom flags from the settings (`catkinCustomBuildFlags`)
* `build current package with dependencies` will run a simple `catkin build --this`.

**Comment by stribor14** [comment]
Thank you for responding so promptly! I think both of those options are beneficial

I saw this morning that it has already been updated, kudos!
