### ISSUE TITLE
Support workspaces not extending another result space

### ISSUE THREAD

**Issue by ptrckschcknbch** [betwo/vscode-catkin-tools#55]
Hi, 
first of all: Thanks for this extension. Great work!

Now my issue:
I have a workspace, which is not extending any other result space. `catkin config` returns the following:
```
------------------------------------------------------------------
Profile:                     default
Extending:                   None
Workspace:                   /home/patrick/workspace/my_project
------------------------------------------------------------------
Build Space:        [exists] /home/patrick/workspace/my_project/build
Devel Space:        [exists] /home/patrick/workspace/my_project/devel
Install Space:      [exists] /home/patrick/workspace/my_project/install
Log Space:          [exists] /home/patrick/workspace/my_project/logs
Source Space:       [exists] /home/patrick/workspace/my_project/src
DESTDIR:            [unused] None
------------------------------------------------------------------
Devel Space Layout:          merged
Install Space Layout:        merged
------------------------------------------------------------------
Additional CMake Args:       -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
------------------------------------------------------------------
Buildlisted Packages:        None
Skiplisted Packages:         None
------------------------------------------------------------------
Workspace configuration appears valid.
------------------------------------------------------------------
```

Opening this workspace in VSCode results in the following pop-ups (it is stuck there):
_Warning: This workspace is not initialized._
_Info: Loading catkin_tools workspace 'my_project': Initializing workspace_
(Sorry, for some reason I'm not able to upload the screenshot here..)

My current assumption is that the root cause might be [this function](https://github.com/betwo/vscode-catkin-tools/blob/3ad24e234dafd220faf6a36e313e37502336159e/src/catkin_tools/catkin_workspace_provider.ts#L218) as it seems to expect an initialized workspace to extend another result space.

Versions:
VSCode: 1.79.2
catkin-tools: 4.8.1

**Comment by betwo** [comment]
Hi @ptrckschcknbch, thank you for the report.

I was able to reproduce this and will create a CI configuration for Ubuntu 22.04 that should cover the issue.
Finding a fix should hopefully not take too long.

**Comment by betwo** [comment]
After some hiccups I finally found a way to add such a test.
In that docker (Ubuntu 22.04) all integration tests are running again.

Unfortunately, I currently don't have access to an Ubuntu 22.04 system. Do you mind going for a test run with the 4.8.2 (pre-release) version?
That would be awesome :)

If the bug is not fixed, I'll set up a newer machine myself.

**Comment by ptrckschcknbch** [comment]
Awesome. Thanks for the quick fix.
Sure, I will test it on my Ubuntu 22.04 system (will take till Monday, though). I'll post the result here.

**Comment by ptrckschcknbch** [comment]
Hi @betwo,
I tested the fix on my system and it seems to be working fine. Thank you :+1: 

**Versions:**
Ubuntu 22.04.2 LTS
VSCode 1.79.2
catkin-tools 4.8.2

**Comment by betwo** [comment]
Thank you for testing, @ptrckschcknbch.
I'll properly release this with 4.8.3 in a few minutes.

Cheers!
